# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  image_name: "aminhaimg"
  tag_name: "estagandatag"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      uses: ./.github/actions/maven_build
    - name: Create docker
      uses: ./.github/actions/dockerbuild
      with:
        image_name: $image_name
        tag_name: $tag_name
    - name: gravar artefacto
      run: docker save -o ${{env.image_name}}.tar ${{env.image_name}}:${{env.tag_name}}
    - uses: actions/upload-artifact@v4
      with:
        name: artifact_name
        path: ${{env.image_name}}.tar










  newjob:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
      name: my-artifact
    - name: Listar o docker image
      run: docker image ls




  
